### ISSUE TITLE
스낵코드

### ISSUE THREAD

**Issue by iamappple** [Protocol-Inc/protocol-workspace#4]
### Details 
코드 컨텐츠 제공 게시판. 목록과 상세 화면으로 구성되어 있습니다. 

### Document 
**기획/디자인 Figma** [Link ](https://www.figma.com/file/KPefHQGmdjb1xfCUDtohHT/Protocol?node-id=193%3A56)
![image](https://user-images.githubusercontent.com/55983122/80315778-c0a5f500-8834-11ea-9f10-e057c08a5a85.png)

### Task
- [x] 기획/디자인 @iamappple 
- [ ] 스낵코드 - 목록 UI @ryancho 
- [ ] 스낵코드 - 상세 UI  @ryancho 
- [ ] 개발 @RiverMinSeo
